# Generated by Django 3.1.2 on 2021-06-19 16:06

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Title')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Longitude')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Marker',
                'verbose_name_plural': 'Markers',
            },
        ),
        migrations.CreateModel(
            name='MarkerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/', verbose_name='Image')),
                ('order', models.IntegerField(blank=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='map.marker')),
            ],
        ),
    ]
