# Generated by Django 3.1.2 on 2021-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=18, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Longitude'),
        ),
    ]
